.travis.yml:
  sudo: true
  dist: trusty
  addons:
    apt:
      packages:
        - libvirt-bin
        - libvirt-dev
scripts/build.sh:
  cgo_enabled: true
scripts/deps.sh:
  packages:
    - github.com/smartystreets/goconvey # NOTE: this should be moved to godep/glide
    - github.com/stretchr/testify/mock
